### ISSUE TITLE
When hitting a breakpoint on Visual Studio the mouse slows down for several seconds before working again

### ISSUE THREAD

**Issue by marcojak** [TolikPylypchuk/SharpHook#37] opened 2023-03-05 18:58 UTC
Hi,
I'm using this plugin in my application and as per title, when I debug my app and I hit a breakpoint, the mouse lags for several seconds before starting to work again.
I have no problems in the app but this makes the debugging of my app incredible frustrating.
Is there anything I can do to solve this issue?

Thank you very much.

**Comment by TolikPylypchuk** [comment] 2023-03-06 19:03
Hi! Thanks for asking!

I've also noticed mouse lagging when debugging an app which uses SharpHook. I think this is a Visual Studio thing more than it's a SharpHook thing. I've tried debugging in Rider and VS Code and there was no mouse lag in them.

Honestly, I don't really know what I can do to fix this (or even if I can do anything), but I'll leave the issue open for now.

**Comment by CodyLyttle** [comment] 2023-03-10 11:37
It's certainly annoying and unfortunately other libraries I've used, including my own, have all suffered from the same issue. 

It's been a while since I've worked on hooks, but I always assumed it was a caused by pausing the application before the current event has had a chance to call the next hook in the chain.

**Comment by oli-g-sk** [comment] 2023-05-28 14:26
> I think this is a Visual Studio thing more than it's a SharpHook thing. I've tried debugging in Rider and VS Code and there was no mouse lag in them.

I'm debugging in Rider and experiencing the same issue. Maybe there's a setting in the IDE which affects this? I have no idea where to even begin looking, though 😢

**Comment by TolikPylypchuk** [comment] 2023-05-29 17:27
I'll try to look into it, but tbh, I don't know where to even begin as well.

**Comment by grofit** [comment] 2023-06-03 19:22
I thought it was something wrong I was doing, but as a Rider user I also get this slowdown/lag in debug mode

**Comment by TolikPylypchuk** [comment] 2023-07-05 21:43
I've looked into this issue again, and this really has to do with how Windows handles low-level global hooks. I don't think there's anything we can do about it.

Here's a [StackOverflow discussion about the issue](https://stackoverflow.com/questions/22130167/low-level-mouse-hook-mouse-freeze-on-breakpoint), and here's the [same issue](https://github.com/gmamaladze/globalmousekeyhook/issues/76) in another global hook library for .NET.

I've tried to create a helper class which destroys and recreates the global hook when debugging but didn't manage to create a usable version - there's just too much overhead, and the code becomes horrible.

I'm going to close this issue as won't-fix, but we can continue the discussion, and if anything comes up, I can always reopen it.

**Closed by TolikPylypchuk** 2023-07-05 21:43 UTC
Labels: wontfix

**Comment by flyingpie** [comment] 2024-01-29 22:39
> I've looked into this issue again, and this really has to do with how Windows handles low-level global hooks. I don't think there's anything we can do about it.
> 
> Here's a [StackOverflow discussion about the issue](https://stackoverflow.com/questions/22130167/low-level-mouse-hook-mouse-freeze-on-breakpoint), and here's the [same issue](https://github.com/gmamaladze/globalmousekeyhook/issues/76) in another global hook library for .NET.
> 
> I've tried to create a helper class which destroys and recreates the global hook when debugging but didn't manage to create a usable version - there's just too much overhead, and the code becomes horrible.
> 
> I'm going to close this issue as won't-fix, but we can continue the discussion, and if anything comes up, I can always reopen it.

Hey @TolikPylypchuk!

Would it be doable to have a filter on the incoming events, so we can turn off mouse events? That could alleviate the problem, at least for users that only need keyboard events.

**Comment by TolikPylypchuk** [comment] 2024-01-30 06:51
Hi @flyingpie! Currently it's not possible since both a keyboard hook and a mouse hook are always created. But I'll think of a way to make it possible to only create one of them.

**Comment by AlizerUncaged** [comment] 2024-02-10 18:07
Have you found out a way? maybe make it possible to have an option to only hook keyboard or mouse, a way to make them not hook at the same time

**Comment by TolikPylypchuk** [comment] 2024-02-10 20:58
I didn't have time yet to look into it, but I'll add this possibility soon.

**Comment by TolikPylypchuk** [comment] 2024-02-24 16:23
I've just released version 5.3.0 which adds the ability to run keyboard-only or mouse-only hooks. This will help with debugging if you only need to handle keyboard events. It can be done the following way (this works for other hooks as well):

```c#
 var hook = new SimpleGlobalHook(GlobalHookType.Keyboard);
```

This way the mouse hook will not be created at all when `hook.Run()` or `hook.RunAsync()` is called and so the mouse cursor will not slow down when a breakpoint is hit.

Of course, this will not really help if you need to handle mouse events.

**Comment by Linlccc** [comment] 2025-07-18 15:05
> I've looked into this issue again, and this really has to do with how Windows handles low-level global hooks. I don't think there's anything we can do about it.
> 
> Here's a [StackOverflow discussion about the issue](https://stackoverflow.com/questions/22130167/low-level-mouse-hook-mouse-freeze-on-breakpoint), and here's the [same issue](https://github.com/gmamaladze/globalmousekeyhook/issues/76) in another global hook library for .NET.
> 
> I've tried to create a helper class which destroys and recreates the global hook when debugging but didn't manage to create a usable version - there's just too much overhead, and the code becomes horrible.
> 
> I'm going to close this issue as won't-fix, but we can continue the discussion, and if anything comes up, I can always reopen it.

@TolikPylypchuk Is there any way to do breakpoint callback in C#
If so, we can stop hooking before entering the breakpoint, exit the breakpoint and then start

**Comment by Linlccc** [comment] 2025-07-18 16:24
This is a bit cumbersome
1. First, wrap up the possible breaking points
2. Break points in code block
And the breaking point is not necessarily all in a block, so that every place needs to be done, and it also needs to be removed manually.


My previous idea was whether there are any underlying APIs that support breakpoint interception, but there seems to be no such way
