### ISSUE TITLE
After the keyboard hook is activated, the Chinese input method candidate word toolbar cannot be displayed

### ISSUE THREAD

**Issue by KevinL2015** [TolikPylypchuk/SharpHook#115] opened 2024-07-23 07:52 UTC
在UOS系统下，使用自带的demo，运行后，UOS自带的中文输入法无法显示候选词栏不显示。这个可能是什么原因引起的？
Under the UOS system, when running the built-in demo, the Chinese input method provided by UOS cannot display the candidate word column. What could be the possible cause of this?

我测试了多个输入法，部分输入法存在这个情况。
I have tested multiple input methods, and some of them have this issue.

**Comment by KevinL2015** [comment] 2024-07-24 07:16
将nuget包版本降到3.1.3问题消失。
Reduce the version of the Nuget package to 3.1.3 and the issue will disappear.

**Comment by TolikPylypchuk** [comment] 2024-07-24 14:37
Hello! Thanks for posting this issue!

Unfortunately, I'm not sure what can be the cause of this issue, as I've never worked with (and have never even seen) Chinese input methods, and I don't have the capacity to research them at this moment. As such, I'm not going to close this issue, but I'm not going to look into it either. Maybe, someone from the community can help here?

Also, please use only English as the language for the issue title, description and comments.

**Comment by KevinL2015** [comment] 2024-07-25 03:27
Thanks for your reply. and sorry for my poor English.
I found that libuiohook1.2 is working properly, but 1.3 has this issue

**Comment by TolikPylypchuk** [comment] 2024-07-25 20:10
No need to apologize for English skills, as long as I can understand, it's all good :)

If you could also figure out which exact change made it not work properly, it would be great.

**Comment by TolikPylypchuk** [comment] 2024-09-27 18:54
I'm closing this issue due to inactivity and inability to fix it, but we can continue the discussion, and I will reopen it if anything comes up.

**Closed by TolikPylypchuk** 2024-09-27 18:54 UTC
Labels: help wanted

**Comment by TolikPylypchuk** [comment] 2025-07-23 06:39
Starting from version 6.2.0, there is a workaround for this issue, as mentioned in #140 (duplicating it here for visibility):

```c#
UioHookProvider.Instance.KeyTypedEnabled = false;
```

This disables `KeyTyped` events which interfere with the Chinese input method.
