### ISSUE TITLE
How to get ScanCode

### ISSUE THREAD

**Issue by RobinGitHub** [TolikPylypchuk/SharpHook#44] opened 2023-04-20 03:43 UTC

**Comment by TolikPylypchuk** [comment] 2023-09-28 18:58
Hi @RobinGitHub! Could you please add a description for this issue? What the problem is and what is your use case, for example?

**Comment by RobinGitHub** [comment] 2023-10-07 01:08
How to obtain the Scan Code of a key press ``

**Comment by TolikPylypchuk** [comment] 2023-10-08 11:26
Unfortunately, getting the scan code in the event handler is not supported. Scan codes are hardware- or driver-dependent and really low-level. Are you sure you want an actual scan code, and not the OS-specific virtual key code (`RawCode`)?

I'm not currently going to add scan codes to keyboard events currently, but you can make a pull-request if you're up to the task (it should be implemented in [libuiohook](https://github.com/TolikPylypchuk/libuiohook) though).

I'm going to close this issue, but we can continue the discussion.

**Closed by TolikPylypchuk** 2023-10-08 11:26 UTC
Labels: needs more info
