### ISSUE TITLE
Visual studio debugger lags when a breakpoint is hit and the SharpHook is running. 

### ISSUE THREAD

**Issue by SqueakyBed** [TolikPylypchuk/SharpHook#55] opened 2023-07-29 21:54 UTC
So I have this

`public static void Initialize()
{
    var hook = new TaskPoolGlobalHook(new TaskPoolGlobalHookOptions(1, true));
    hook.KeyPressed += Hook_KeyPressed;
    hook.RunAsync(); 
}
private static void Hook_KeyPressed(object sender, KeyboardHookEventArgs e)
{
   
}`

And it is called from a .Net Maui application entry point. 

Whenever I start debugging and a break point is triggered and I try to step into/over/out code or even move the mouse the debugger lags and the mouse freezes for a few seconds until I stop moving it then it freezes again as soon as I make another move. 
It seems like it has something to do with the mouse move messages, It's as if the mouse move messages are being queued while the debugger is frozen and then batch processed when I walk the debugger.

The issue disappears if I Omit hook.RunAsync(); so I know it;s cause by SharpHook.

I am using Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.7.0 Preview 5.0

it also happens on the Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.5

**Comment by TolikPylypchuk** [comment] 2023-07-30 20:45
Hi! Thanks for posting this issue!

Unfortunately, this problem is caused by the way Windows runs global keyboard/mouse hooks, it's not caused by SharpHook-specific code, so there's nothing I can really do about it. I know it's inconvenient - I sometimes run into this issue as well.

I'm going to close this as a duplicate of issue #37. We can continue the discussion there if you'd like. You can also view [the StackOverflow question about this issue](https://stackoverflow.com/questions/22130167/low-level-mouse-hook-mouse-freeze-on-breakpoint).

**Closed by TolikPylypchuk** 2023-07-30 20:45 UTC
Labels: duplicate, wontfix
