### ISSUE TITLE
Only special keys (shift, control, &c.) trigger events. (at least not on MacOS)

### ISSUE THREAD

**Issue by Albator11** [TolikPylypchuk/SharpHook#56] opened 2023-08-19 22:57 UTC
I can't figure out how to know if keys A-Z, 0-9, &c. are pressed or released... special keys like shift, control, option, &c. work though.

I even tried the [sample](https://github.com/TolikPylypchuk/SharpHook/tree/master/SharpHook.Sample) which explicitly shows you're supposed to use the `q` key to quit... but it doesn't work for me.

I'm using MacOS 12.6.8 and SharpHook 5.0.0.

EDIT: I guess this would actually be a problem with libuiohook rather then SharpHook which is just the C# wrapper. :( whoops.

**Comment by Albator11** [comment] 2023-08-19 23:45
I found a fix. It turns out running as sudo is what made it work for me as I describe [here](https://github.com/kwhat/libuiohook/issues/175#issuecomment-1685132380).

**Comment by TolikPylypchuk** [comment] 2023-08-20 15:56
Hi! Thanks for posting an issue! If I understand correctly, you mean that the global hook doesn't raise any events when you press keys like A. Could you please share a small code snippet which I can use to try to reproduce the issue? I've tested SharpHook numerous times on macOS and it worked for me without problems (it was on macOS 13, but I'm sure that macOS 12 wouldn't be that different).

Running the app as `root` should not be a requirement. What is needed though is to enable access to the accessibility APIs for the app (but I guess the app has it, or else the hook wouldn't run at all).

**Comment by Albator11** [comment] 2023-08-20 23:20
Sure, this is what I was using to test it out. (I also tried `LogSource` which I left commented out)
This seems to be an issue with uiohook itself rather than your wrapper, because I tried compiling and running one of the demos uiohook has, and it behaved the same.

And yes, iTerm has accessibility API privileges... which I assume is enough, especially since (like you said) it shouldn't run at all if it doesn't have those privileges.

```csharp
using TaskPoolGlobalHook hook = new();

hook.KeyPressed += (sender, args) => {
    Console.WriteLine(args.Data);
};
hook.KeyReleased += (sender, args) => {
    Console.WriteLine(args.Data);
};
hook.KeyTyped += (sender, args) => {
    Console.WriteLine(args.Data);
};

// using LogSource logSource = LogSource.Register(LogLevel.Debug);
// logSource.MessageLogged += (sender, args) => {
//     Console.WriteLine(args.LogEntry);
// };

hook.Run();
```

**Comment by Albator11** [comment] 2023-08-21 18:40
I should have a standard setup... I'm just using a MacBook Pro Mid 2015 with it's built-in keyboard.
I don't know of any apps I have that might be remapping keys... and that wouldn't explain why it works with sudo, does it?

OH, is it possibly something to do with this?
`event_to_unicode [714]: Using no runloop for key typed events.`

Anyway, here's the debug log using `LogEntry.FullText`. (hopefully it's what you wanted)
I typed shift, command, `aaaaasdf`, return (so that there'd be a line break after the characters), shift, and then control+c.
```
hook_set_dispatch_proc [53]: Setting new dispatch callback to 0x10a153124.
hook_run [364]: Accessibility API is enabled.
hook_run [375]: CFRunLoopGetCurrent successful.
create_event_runloop_info [277]: CGEventTapCreate Successful.
create_event_runloop_info [289]: CFMachPortCreateRunLoopSource successful.
create_event_runloop_info [307]: CFRunLoopObserverCreate successful.
dispatch_event [63]: Dispatching event type 1.
dispatch_modifier_change [339]: Modifiers Changed for key 0X38. (0X20102)
dispatch_key_press [131]: Key 0XA010 pressed. (0X38)
dispatch_event [63]: Dispatching event type 4.
event_to_unicode [714]: Using no runloop for key typed events.
dispatch_modifier_change [339]: Modifiers Changed for key 0X38. (0X100)
dispatch_key_release [186]: Key 0XA010 released. (0X38)
dispatch_event [63]: Dispatching event type 5.
dispatch_modifier_change [339]: Modifiers Changed for key 0X37. (0X100108)
dispatch_key_press [131]: Key 0XA09D pressed. (0X37)
dispatch_event [63]: Dispatching event type 4.
event_to_unicode [714]: Using no runloop for key typed events.
dispatch_modifier_change [339]: Modifiers Changed for key 0X37. (0X100)
dispatch_key_release [186]: Key 0XA09D released. (0X37)
dispatch_event [63]: Dispatching event type 5.
aaaaasdf
dispatch_modifier_change [339]: Modifiers Changed for key 0X38. (0X20102)
dispatch_key_press [131]: Key 0XA010 pressed. (0X38)
dispatch_event [63]: Dispatching event type 4.
event_to_unicode [714]: Using no runloop for key typed events.
dispatch_modifier_change [339]: Modifiers Changed for key 0X38. (0X100)
dispatch_key_release [186]: Key 0XA010 released. (0X38)
dispatch_event [63]: Dispatching event type 5.
dispatch_modifier_change [339]: Modifiers Changed for key 0X3B. (0X40101)
dispatch_key_press [131]: Key 0XA011 pressed. (0X3B)
dispatch_event [63]: Dispatching event type 4.
event_to_unicode [714]: Using no runloop for key typed events.
```

**Comment by Albator11** [comment] 2023-08-22 17:53
Yes, mouse events work fine with and without sudo. (movement, scrolling, clicking)

Alright, I'll work on messing around with `CGEventTapCreate`. (hopefully later today or tomorrow...)

**Comment by TolikPylypchuk** [comment] 2023-08-23 06:11
I'm glad that you got it working, but the interesting thing is that it should've worked even without access to input monitoring. I will try to look into it in more detail a little later.

**Comment by TolikPylypchuk** [comment] 2023-12-16 21:51
I've tried looking into this issue a couple times since the last activity, and I couldn't find anything. Since I cannot reproduce this issue, and you have a workaround for it, I think it's fine to close it. We can continue the discussion or reopen this issue if new stuff comes up.

**Closed by TolikPylypchuk** 2023-12-16 21:51 UTC
Labels: bug, wontfix, libuiohook issue
