### ISSUE TITLE
Trying to use on Mac (.NET MAUI) throws exception

### ISSUE THREAD

**Issue by leosimanonok** [TolikPylypchuk/SharpHook#31] opened 2023-01-19 20:37 UTC
Tried to add package through nuget on VS for Mac Preview (most up-to date version), and get	{System.DllNotFoundException: uiohook    at SharpHook.Native.UioHook.SetDispatchProc(DispatchProc dispatchProc, IntPtr userData)    at SharpHook.GlobalHookBase.<>c__DisplayClass16_0.<RunAsync>b__0()}	System.DllNotFoundException

when running 
`var hook = new TaskPoolGlobalHook();
  hook.KeyPressed += OnKeyPressed;
  await hook.RunAsync();
`

**Comment by TolikPylypchuk** [comment] 2023-01-20 07:16
Hi! Thanks for using SharpHook! Yes, there's currently a bug on macOS - the `libuiohook.dylib` file is not copied to the build directory on macOS for some reason. I haven't had the chance to investigate it yet as I don't have a Mac. You can find a workaround for this issue in [this discussion thread](https://github.com/TolikPylypchuk/SharpHook/discussions/22#discussioncomment-4184955).

Also, I'm going to close this issue as a duplicate of issue #26. If you want to discuss it further, let's move the discussion to that issue. If you believe that this is a separate issue, we can always reopen this issue instead.

**Closed** 2023-01-20 07:16 UTC
Labels: bug, duplicate

**Comment by leosimanonok** [comment] 2023-01-20 12:16
Thank you so much!

Leo
________________________________

**Comment by TolikPylypchuk** [comment] 2023-08-10 20:58
Hi @leosimanonok! Mac Catalyst support has been added in version 5.0.0 which I've just released, so this issue can be closed as completed now :)
