### ISSUE TITLE
Mouse simulation uses a different "coordinate mapping" than the coordinates reported by the hook

### ISSUE THREAD

**Issue by bj-rn** [TolikPylypchuk/SharpHook#66] opened 2023-10-06 15:15 UTC
Hi,

I just recently updated my wrapper to SharpHook 5.0.0 (Great work!)  and immediately got [feedback](https://github.com/bj-rn/VL.IO.MouseKeyGlobal/issues/1) concerning mouse simulation. I'll quote the issue here for better understanding:

> On my 3 sceen setup (the middle sceen being the primary screen) the mouse position _[as returned by the hook or windows]_ is not equal to the position that can be input to the MouseSimulator.
> 
> When the simulator gets coordinates 1280/720 the pointer should appear at the green position. However, it actually does appear on the red position (which is not intuitive).
![image](https://github.com/TolikPylypchuk/SharpHook/assets/1632591/3c4f82c3-86b7-4b2f-88e0-15c288bacfc0)

The mouse simulator (now)  uses a different "coordinate mapping" than the coordinates that are returned by the hook or reported by windows. I guess this is due the following change to _libuihook_ https://github.com/TolikPylypchuk/libuiohook/pull/1
I have to agree with [mh](https://github.com/mhusinsky) who made me aware of the issue, the behaviour is pretty unintuitive. 

I can of course add a workaround by remapping the coordinates but this also implies adding some kind screen info functionality.

Could the conversion be handled internally by the mouse simulator? 

Regards

**Comment by TolikPylypchuk** [comment] 2023-10-06 17:13
Hi! Thanks for asking! This is a known issue and it's already been fixed - it will be available in version 5.1.0. There are a couple more things I want to fix before releasing it, but hopefully, it'll be soon.

This issue is a duplicate of issue #58, but I'm not going to close it as I haven't released the fix yet. Also, you can try out the fixed version of libuiohook as described in [my comment on that issue](https://github.com/TolikPylypchuk/SharpHook/issues/58#issuecomment-1732402428).

**Comment by bj-rn** [comment] 2023-10-06 17:16
Ah sorry didn't check the closed issues. Thanks.

**Comment by TolikPylypchuk** [comment] 2023-10-06 17:18
No problem, it was closed a little prematurely 😄

**Comment by TolikPylypchuk** [comment] 2023-10-08 20:37
Version 5.1.0 was released today, and it contains the fix for this issue. I'm still closing it as a duplicate though :)

**Closed by TolikPylypchuk** 2023-10-08 20:37 UTC
Labels: bug, duplicate
