### ISSUE TITLE
Eception in published NET6-app

### ISSUE THREAD

**Issue by dtagesson** [TolikPylypchuk/SharpHook#13] opened 2022-07-01 08:26 UTC
Unfortunately I still have a problem very similar to issue #12. This time it works fine in Visual Studio using SharpHook 3.0.1, but when we deploy the app on a client it crashes I'm a afraid. I attached some screen captures from Windows Event Viewer. We publish as a self contained .NET6 application.

I tested to use the test project I sent you in #12 and published it as a self contained app and could reproduce it. So if you use that testproject and Publish using the settings from the attached VS screen capture I hope you can reproduce it. Otherwise just let me know if there's anything else you need from me!
Cheers! 

![SharpHookError 2](https://user-images.githubusercontent.com/71884409/176855552-a70698f0-2590-4aba-8c5e-168ab17acc90.png)
![SharpHookError 3](https://user-images.githubusercontent.com/71884409/176855554-1b782b43-f505-4f1d-811d-714f99ec46d5.png)
![SharpHook PublishSettings](https://user-images.githubusercontent.com/71884409/176855557-fbf01d0a-5930-44ae-8167-9e14cca49f62.png)
.

**Comment by TolikPylypchuk** [comment] 2022-07-01 09:10
Hi! Thanks for posting this issue! I will look into it shortly.

**Comment by TolikPylypchuk** [comment] 2022-07-01 09:22
Yup, just published your test app myself. It doesn't work for x86 (with the same error as you described), but it does work for x64. So I have a question - do you really need x86 support? If not, then publish the app for x64, and there'll be no issue.

I'm closing this issue as a duplicate of #10. If you want to follow up on this problem, then let's move the discussion to that issue.

**Closed by TolikPylypchuk** 2022-07-01 09:22 UTC
Labels: bug, duplicate

**Comment by TolikPylypchuk** [comment] 2022-07-01 14:23
Version 3.0.2 is released and this issue is fixed there.

**Comment by dtagesson** [comment] 2022-07-01 14:31
Awesome. Thanks!
